-- Initial Prisma baseline for offset.io. This is intentionally not applied to
-- the pre-existing development database; baseline that database before deploy.
CREATE TABLE "User" ("id" TEXT NOT NULL PRIMARY KEY,"email" TEXT NOT NULL,"passwordHash" TEXT NOT NULL,"name" TEXT NOT NULL,"role" TEXT NOT NULL DEFAULT 'USER',"createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" DATETIME NOT NULL);
CREATE TABLE "Profile" ("id" TEXT NOT NULL PRIMARY KEY,"userId" TEXT NOT NULL,"region" TEXT NOT NULL DEFAULT 'GLOBAL',"dietPattern" TEXT NOT NULL DEFAULT 'MIXED',"householdSize" INTEGER NOT NULL DEFAULT 1,"primaryTransport" TEXT NOT NULL DEFAULT 'CAR_PETROL',"targetReductionPct" REAL NOT NULL DEFAULT 20.0,"monthlyBudget" REAL NOT NULL DEFAULT 2000.0,"currency" TEXT NOT NULL DEFAULT 'USD',"onboardingComplete" BOOLEAN NOT NULL DEFAULT false,"createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" DATETIME NOT NULL,CONSTRAINT "Profile_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE TABLE "EmissionFactor" ("id" TEXT NOT NULL PRIMARY KEY,"category" TEXT NOT NULL,"activity" TEXT NOT NULL,"subtype" TEXT NOT NULL,"region" TEXT NOT NULL DEFAULT 'GLOBAL',"unit" TEXT NOT NULL,"factor" REAL NOT NULL,"source" TEXT NOT NULL,"sourceUrl" TEXT,"methodologyNote" TEXT,"validFrom" DATETIME,"validTo" DATETIME,"confidenceLevel" TEXT NOT NULL DEFAULT 'HIGH',"isActive" BOOLEAN NOT NULL DEFAULT true,"createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" DATETIME NOT NULL);
CREATE TABLE "Activity" ("id" TEXT NOT NULL PRIMARY KEY,"userId" TEXT NOT NULL,"category" TEXT NOT NULL,"activityType" TEXT NOT NULL,"subtype" TEXT NOT NULL,"frequency" TEXT NOT NULL DEFAULT 'MONTHLY',"quantity" REAL NOT NULL,"unit" TEXT NOT NULL,"region" TEXT NOT NULL DEFAULT 'GLOBAL',"createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" DATETIME NOT NULL,CONSTRAINT "Activity_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE TABLE "Calculation" ("id" TEXT NOT NULL PRIMARY KEY,"userId" TEXT NOT NULL,"category" TEXT NOT NULL,"activityType" TEXT NOT NULL,"annualEmissionsKg" REAL NOT NULL,"monthlyEmissionsKg" REAL NOT NULL,"dailyEmissionsKg" REAL NOT NULL,"factorUsed" REAL NOT NULL,"formula" TEXT NOT NULL,"confidenceLevel" TEXT NOT NULL DEFAULT 'HIGH',"minEmissionsKg" REAL NOT NULL,"maxEmissionsKg" REAL NOT NULL,"breakdownJson" TEXT NOT NULL,"createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "Calculation_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE TABLE "Scenario" ("id" TEXT NOT NULL PRIMARY KEY,"userId" TEXT NOT NULL,"name" TEXT NOT NULL,"description" TEXT,"isBaseline" BOOLEAN NOT NULL DEFAULT false,"totalAnnualEmissionsKg" REAL NOT NULL,"estimatedCostDeltaMonthly" REAL NOT NULL DEFAULT 0.0,"createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" DATETIME NOT NULL,CONSTRAINT "Scenario_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE TABLE "ScenarioActivity" ("id" TEXT NOT NULL PRIMARY KEY,"scenarioId" TEXT NOT NULL,"category" TEXT NOT NULL,"activityType" TEXT NOT NULL,"subtype" TEXT NOT NULL,"frequency" TEXT NOT NULL DEFAULT 'MONTHLY',"quantity" REAL NOT NULL,"unit" TEXT NOT NULL,"region" TEXT NOT NULL DEFAULT 'GLOBAL',CONSTRAINT "ScenarioActivity_scenarioId_fkey" FOREIGN KEY ("scenarioId") REFERENCES "Scenario" ("id") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE TABLE "Recommendation" ("id" TEXT NOT NULL PRIMARY KEY,"userId" TEXT,"title" TEXT NOT NULL,"explanation" TEXT NOT NULL,"category" TEXT NOT NULL,"estimatedReductionKg" REAL NOT NULL,"estimatedCostMonthly" REAL NOT NULL DEFAULT 0.0,"difficulty" TEXT NOT NULL DEFAULT 'MEDIUM',"priority" TEXT NOT NULL DEFAULT 'MEDIUM',"prerequisites" TEXT,"createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "Recommendation_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE TABLE "CarbonGoal" ("id" TEXT NOT NULL PRIMARY KEY,"userId" TEXT NOT NULL,"targetAnnualEmissionsKg" REAL NOT NULL,"targetMonthlyEmissionsKg" REAL NOT NULL,"reductionPercentage" REAL NOT NULL,"targetYear" INTEGER NOT NULL DEFAULT 2026,"status" TEXT NOT NULL DEFAULT 'ACTIVE',"createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" DATETIME NOT NULL,CONSTRAINT "CarbonGoal_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE TABLE "DiaryEntry" ("id" TEXT NOT NULL PRIMARY KEY,"userId" TEXT NOT NULL,"date" DATETIME NOT NULL,"category" TEXT NOT NULL,"activityType" TEXT NOT NULL,"subtype" TEXT NOT NULL,"quantity" REAL NOT NULL,"unit" TEXT NOT NULL,"emissionsKg" REAL NOT NULL,"notes" TEXT,"createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "DiaryEntry_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE TABLE "Insight" ("id" TEXT NOT NULL PRIMARY KEY,"userId" TEXT NOT NULL,"title" TEXT NOT NULL,"description" TEXT NOT NULL,"category" TEXT NOT NULL,"severity" TEXT NOT NULL DEFAULT 'INFO',"isAnomaly" BOOLEAN NOT NULL DEFAULT false,"anomalyScore" REAL NOT NULL DEFAULT 0.0,"createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "Insight_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");
CREATE UNIQUE INDEX "Profile_userId_key" ON "Profile"("userId");
CREATE INDEX "EmissionFactor_category_activity_region_idx" ON "EmissionFactor"("category","activity","region");
CREATE UNIQUE INDEX "EmissionFactor_category_activity_subtype_region_unit_isActive_key" ON "EmissionFactor"("category","activity","subtype","region","unit","isActive");
CREATE INDEX "Activity_userId_category_idx" ON "Activity"("userId","category");
CREATE INDEX "Scenario_userId_idx" ON "Scenario"("userId");
CREATE INDEX "CarbonGoal_userId_idx" ON "CarbonGoal"("userId");
CREATE INDEX "DiaryEntry_userId_date_idx" ON "DiaryEntry"("userId","date");
CREATE INDEX "Insight_userId_createdAt_idx" ON "Insight"("userId","createdAt");
