/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // Stitch Offset Editorial Color Palette
        'surface': '#fcf9f8',
        'surface-dim': '#dcd9d9',
        'surface-bright': '#fcf9f8',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f6f3f2',
        'surface-container': '#f0edec',
        'surface-container-high': '#ebe7e7',
        'surface-container-highest': '#e5e2e1',
        'surface-variant': '#e5e2e1',
        'on-surface': '#1c1b1b',
        'on-surface-variant': '#444557',
        'inverse-surface': '#313030',
        'inverse-on-surface': '#f3f0ef',
        'outline': '#757689',
        'outline-variant': '#c5c5da',
        'surface-tint': '#273fff',
        'primary': '#001fce',
        'on-primary': '#ffffff',
        'primary-container': '#1a36ff',
        'on-primary-container': '#cacdff',
        'inverse-primary': '#bdc2ff',
        'primary-fixed': '#dfe0ff',
        'primary-fixed-dim': '#bdc2ff',
        'on-primary-fixed': '#000a64',
        'on-primary-fixed-variant': '#0022db',
        'secondary': '#006492',
        'on-secondary': '#ffffff',
        'secondary-container': '#04b3ff',
        'on-secondary-container': '#004261',
        'secondary-fixed': '#c9e6ff',
        'secondary-fixed-dim': '#8aceff',
        'on-secondary-fixed': '#001e2f',
        'on-secondary-fixed-variant': '#004b6f',
        'tertiary': '#851400',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#af1f02',
        'on-tertiary-container': '#ffc3b6',
        'tertiary-fixed': '#ffdad3',
        'tertiary-fixed-dim': '#ffb4a4',
        'on-tertiary-fixed': '#3e0500',
        'on-tertiary-fixed-variant': '#8d1600',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'background': '#fcf9f8',
        'on-background': '#1c1b1b',
        // Specific Spot Colors from Stitch Design
        'cyan-accent': '#00B2FE',
        'coral-accent': '#FF5938',
        'yellow-accent': '#FFDE38',
        'cobalt-accent': '#1A36FF',
      },
      fontFamily: {
        'display': ['"Space Grotesk"', 'sans-serif'],
        'headline': ['"Space Grotesk"', 'sans-serif'],
        'label': ['"Space Grotesk"', 'sans-serif'],
        'body': ['"Work Sans"', 'sans-serif'],
        'sans': ['"Work Sans"', 'sans-serif'],
        'mono': ['monospace'],
      },
      fontSize: {
        'display-hero': ['72px', { lineHeight: '76px', letterSpacing: '-0.04em', fontWeight: '700' }],
        'display-hero-mobile': ['44px', { lineHeight: '48px', letterSpacing: '-0.03em', fontWeight: '700' }],
        'headline-xl': ['48px', { lineHeight: '52px', letterSpacing: '-0.03em', fontWeight: '700' }],
        'headline-xl-mobile': ['32px', { lineHeight: '36px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '38px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '30px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-sm': ['18px', { lineHeight: '24px', letterSpacing: '0', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['15px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['13px', { lineHeight: '20px', fontWeight: '400' }],
        'label-caps-md': ['12px', { lineHeight: '16px', letterSpacing: '0.08em', fontWeight: '700' }],
        'label-caps-sm': ['10px', { lineHeight: '14px', letterSpacing: '0.1em', fontWeight: '700' }],
      },
      spacing: {
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2.5rem',
        'margin': '1.5rem',
        'margin-tablet': '1rem',
        'margin-mobile': '0.75rem',
        'gutter': '0px',
        'gutter-tablet': '0px',
        'gutter-mobile': '0px',
      },
      borderRadius: {
        'none': '0px',
        DEFAULT: '0px',
        'sm': '0px',
        'md': '0px',
        'lg': '0px',
        'xl': '0px',
        '2xl': '0px',
        'full': '9999px',
      },
      boxShadow: {
        'hard-offset': '4px 4px 0px #121212',
        'hard-offset-sm': '2px 2px 0px #121212',
        'hard-offset-blue': '4px 4px 0px #001fce',
      },
    },
  },
  plugins: [],
};
